### ISSUE TITLE
The library should not throw ArgsParsingException when building parser with invalid configurations.

### ISSUE THREAD

**Issue by lxconan** [TW307Cultivation/Args.Parser.Net#1]
The library should not throw `ArgsParsingException` when building parser with invalid configurations.

Please think the following questions:

* What kind of error does `ArgsParsingException` represent?
* When do you throw `ArgumentNullException`, `ArgumentException` and `ArgumentOutOfRangeException`?

**Comment by mengfanx8** [comment]
Fixed, change ArgsParsingException to internal, 3a14f68f22b817fc2638990f361bd4240dc63fc8
