### ISSUE TITLE
The error structure accessor should not be all public.

### ISSUE THREAD

**Issue by lxconan** [TW307Cultivation/Args.Parser.Net#3]
https://github.com/TW307Cultivation/Args.Parser.Net/blob/48f7e208db9a7325e1039e29fb486cb1b6ad0f09/src/Args.Parser/Core/ArgsParsingError.cs#L6

**Comment by mengfanx8** [comment]
Fixed, bca67689f2daf95a9089b8efd79071eaabd187c1
